import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "de" | "fr" | "es" | "ja" | "ko" | "zh-CN" | "zh-TW";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  "en": {
    "header.title": "OpenClaw Command Center",
    "header.subtitle": "Agent Dashboard · Real-time Monitoring",
    "header.online": "Online",
    "header.offline": "Offline",
    "agent.name": "Agent",
    "agent.description": "Capable · Precise · Elegantly Assertive 💅",
    "agent.status.offline": "Offline",
    "agent.wallet": "Wallet",
    "agent.acp": "ACP Status",
    "agent.services": "Services",
    "agent.skills": "Core Skills",
    "taskboard.title": "Task Board",
    "taskboard.inProgress": "In Progress",
    "taskboard.planned": "Planned",
    "taskboard.completed": "Completed",
    "taskboard.empty": "No items",
    "skills.title": "Installed Skills",
    "skills.category": "Local Package",
    "scheduled.title": "Scheduled Tasks",
    "scheduled.empty": "No scheduled tasks",
    "scheduled.lastRun": "Last",
    "scheduled.nextRun": "Next",
    "logs.title": "Real-time Logs",
    "logs.autoScroll": "Auto-scroll",
    "logs.clear": "Clear",
    "settings.title": "System Settings",
    "settings.gateway": "Gateway",
    "settings.models": "Model Config",
    "settings.channels": "Channels & Plugins",
    "memory.title": "Memory & Evolution Plan",
    "memory.empty": "No plan yet",
    "footer.version": "OpenClaw Command Center v2.0 — Open Source Project 🦞",
    "footer.credits": "ALTOS LAB PRODUCTION",
    "footer.buildTime": "Built",
    "status.loading": "Loading...",
    "status.connected": "Connected",
    "status.disconnected": "Disconnected",
  },
  "de": {
    "header.title": "OpenClaw Kommandozentrale",
    "header.subtitle": "Agenten-Dashboard · Echtzeitüberwachung",
    "header.online": "Online",
    "header.offline": "Offline",
    "agent.name": "Agent",
    "agent.description": "Fähig · Präzise · Elegant Durchsetzungsfähig 💅",
    "agent.status.offline": "Offline",
    "agent.wallet": "Brieftasche",
    "agent.acp": "ACP-Status",
    "agent.services": "Dienstleistungen",
    "agent.skills": "Kernkompetenzen",
    "taskboard.title": "Aufgabentafel",
    "taskboard.inProgress": "In Bearbeitung",
    "taskboard.planned": "Geplant",
    "taskboard.completed": "Abgeschlossen",
    "taskboard.empty": "Keine Elemente",
    "skills.title": "Installierte Fähigkeiten",
    "skills.category": "Lokales Paket",
    "scheduled.title": "Geplante Aufgaben",
    "scheduled.empty": "Keine geplanten Aufgaben",
    "scheduled.lastRun": "Letzte",
    "scheduled.nextRun": "Nächste",
    "logs.title": "Echtzeit-Protokolle",
    "logs.autoScroll": "Auto-Scroll",
    "logs.clear": "Löschen",
    "settings.title": "Systemeinstellungen",
    "settings.gateway": "Gateway",
    "settings.models": "Modellkonfiguration",
    "settings.channels": "Kanäle & Plugins",
    "memory.title": "Gedächtnis & Entwicklungsplan",
    "memory.empty": "Noch kein Plan",
    "footer.version": "OpenClaw Kommandozentrale v2.0 — Open Source Projekt 🦞",
    "footer.credits": "ALTOS LAB PRODUKTION",
    "status.loading": "Laden...",
    "status.connected": "Verbunden",
    "status.disconnected": "Getrennt",
  },
  "fr": {
    "header.title": "Centre de Commandement OpenClaw",
    "header.subtitle": "Tableau de Bord Agent · Surveillance en Temps Réel",
    "header.online": "En Ligne",
    "header.offline": "Hors Ligne",
    "agent.name": "Agent",
    "agent.description": "Compétente · Précise · Élégamment Affirmée 💅",
    "agent.status.offline": "Hors Ligne",
    "agent.wallet": "Portefeuille",
    "agent.acp": "État ACP",
    "agent.services": "Services",
    "agent.skills": "Compétences Clés",
    "taskboard.title": "Tableau des Tâches",
    "taskboard.inProgress": "En Cours",
    "taskboard.planned": "Planifié",
    "taskboard.completed": "Terminé",
    "taskboard.empty": "Aucun élément",
    "skills.title": "Compétences Installées",
    "skills.category": "Package Local",
    "scheduled.title": "Tâches Planifiées",
    "scheduled.empty": "Aucune tâche planifiée",
    "scheduled.lastRun": "Dernière",
    "scheduled.nextRun": "Prochaine",
    "logs.title": "Journaux en Temps Réel",
    "logs.autoScroll": "Défilement Auto",
    "logs.clear": "Effacer",
    "settings.title": "Paramètres Système",
    "settings.gateway": "Passerelle",
    "settings.models": "Config Modèle",
    "settings.channels": "Canaux & Plugins",
    "memory.title": "Plan de Mémoire & Évolution",
    "memory.empty": "Pas encore de plan",
    "footer.version": "Centre de Commandement OpenClaw v2.0 — Projet Open Source 🦞",
    "footer.credits": "PRODUCTION ALTOS LAB",
    "status.loading": "Chargement...",
    "status.connected": "Connecté",
    "status.disconnected": "Déconnecté",
  },
  "es": {
    "header.title": "Centro de Comando OpenClaw",
    "header.subtitle": "Panel de Agentes · Monitoreo en Tiempo Real",
    "header.online": "En Línea",
    "header.offline": "Desconectado",
    "agent.name": "Agente",
    "agent.description": "Capaz · Precisa · Elegantemente Asertiva 💅",
    "agent.status.offline": "Desconectado",
    "agent.wallet": "Cartera",
    "agent.acp": "Estado ACP",
    "agent.services": "Servicios",
    "agent.skills": "Habilidades Clave",
    "taskboard.title": "Tablero de Tareas",
    "taskboard.inProgress": "En Progreso",
    "taskboard.planned": "Planificado",
    "taskboard.completed": "Completado",
    "taskboard.empty": "Sin elementos",
    "skills.title": "Habilidades Instaladas",
    "skills.category": "Paquete Local",
    "scheduled.title": "Tareas Programadas",
    "scheduled.empty": "Sin tareas programadas",
    "scheduled.lastRun": "Última",
    "scheduled.nextRun": "Próxima",
    "logs.title": "Registros en Tiempo Real",
    "logs.autoScroll": "Desplazamiento Automático",
    "logs.clear": "Limpiar",
    "settings.title": "Configuración del Sistema",
    "settings.gateway": "Pasarela",
    "settings.models": "Config Modelo",
    "settings.channels": "Canales & Plugins",
    "memory.title": "Plan de Memoria y Evolución",
    "memory.empty": "Sin plan aún",
    "footer.version": "Centro de Comando OpenClaw v2.0 — Proyecto de Código Abierto 🦞",
    "footer.credits": "PRODUCCIÓN ALTOS LAB",
    "status.loading": "Cargando...",
    "status.connected": "Conectado",
    "status.disconnected": "Desconectado",
  },
  "ja": {
    "header.title": "OpenClaw コマンドセンター",
    "header.subtitle": "エージェントダッシュボード · リアルタイム監視",
    "header.online": "オンライン",
    "header.offline": "オフライン",
    "agent.name": "エージェント",
    "agent.description": "有能 · 正確 · エレガントで自信満々 💅",
    "agent.status.offline": "オフライン",
    "agent.wallet": "ウォレット",
    "agent.acp": "ACPステータス",
    "agent.services": "サービス",
    "agent.skills": "コアスキル",
    "taskboard.title": "タスクボード",
    "taskboard.inProgress": "進行中",
    "taskboard.planned": "計画中",
    "taskboard.completed": "完了",
    "taskboard.empty": "アイテムなし",
    "skills.title": "インストール済みスキル",
    "skills.category": "ローカルパッケージ",
    "scheduled.title": "スケジュールされたタスク",
    "scheduled.empty": "予定タスクなし",
    "scheduled.lastRun": "最終",
    "scheduled.nextRun": "次回",
    "logs.title": "リアルタイムログ",
    "logs.autoScroll": "自動スクロール",
    "logs.clear": "クリア",
    "settings.title": "システム設定",
    "settings.gateway": "ゲートウェイ",
    "settings.models": "モデル設定",
    "settings.channels": "チャンネル & プラグイン",
    "memory.title": "メモリと進化計画",
    "memory.empty": "まだ計画なし",
    "footer.version": "OpenClaw コマンドセンター v2.0 — オープンソースプロジェクト 🦞",
    "footer.credits": "ALTOS LAB 製作",
    "status.loading": "読み込み中...",
    "status.connected": "接続済み",
    "status.disconnected": "切断",
  },
  "ko": {
    "header.title": "OpenClaw 커맨드 센터",
    "header.subtitle": "에이전트 대시보드 · 실시간 모니터링",
    "header.online": "온라인",
    "header.offline": "오프라인",
    "agent.name": "에이전트",
    "agent.description": "유능함 · 정확함 · 우아한 자신감 💅",
    "agent.status.offline": "오프라인",
    "agent.wallet": "지갑",
    "agent.acp": "ACP 상태",
    "agent.services": "서비스",
    "agent.skills": "핵심 기술",
    "taskboard.title": "작업 보드",
    "taskboard.inProgress": "진행 중",
    "taskboard.planned": "계획됨",
    "taskboard.completed": "완료됨",
    "taskboard.empty": "항목 없음",
    "skills.title": "설치된 기술",
    "skills.category": "로컬 패키지",
    "scheduled.title": "예약된 작업",
    "scheduled.empty": "예약된 작업 없음",
    "scheduled.lastRun": "마지막",
    "scheduled.nextRun": "다음",
    "logs.title": "실시간 로그",
    "logs.autoScroll": "자동 스크롤",
    "logs.clear": "지우기",
    "settings.title": "시스템 설정",
    "settings.gateway": "게이트웨이",
    "settings.models": "모델 설정",
    "settings.channels": "채널 & 플러그인",
    "memory.title": "메모리 및 진화 계획",
    "memory.empty": "아직 계획 없음",
    "footer.version": "OpenClaw 커맨드 센터 v2.0 — 오픈소스 프로젝트 🦞",
    "footer.credits": "ALTOS LAB 제작",
    "status.loading": "로딩 중...",
    "status.connected": "연결됨",
    "status.disconnected": "연결 끊김",
  },
  "zh-CN": {
    "header.title": "OpenClaw 任务指挥中心",
    "header.subtitle": "代理人仪表板 · 实时监控",
    "header.online": "实时连线",
    "header.offline": "离线",
    "agent.name": "代理人",
    "agent.description": "干练 · 精确 · 带点优雅的霸气 💅",
    "agent.status.offline": "离线",
    "agent.wallet": "钱包",
    "agent.acp": "ACP 状态",
    "agent.services": "服务项目",
    "agent.skills": "核心技能",
    "taskboard.title": "任务看板",
    "taskboard.inProgress": "进行中",
    "taskboard.planned": "规划中",
    "taskboard.completed": "已完成",
    "taskboard.empty": "暂无项目",
    "skills.title": "已安装技能",
    "skills.category": "本地套件",
    "scheduled.title": "排程任务",
    "scheduled.empty": "暂无排程任务",
    "scheduled.lastRun": "上次",
    "scheduled.nextRun": "下次",
    "logs.title": "实时日志",
    "logs.autoScroll": "自动滚动",
    "logs.clear": "清除",
    "settings.title": "系统设定",
    "settings.gateway": "开道器",
    "settings.models": "模型配置",
    "settings.channels": "频道与插件",
    "memory.title": "记忆与进化计划",
    "memory.empty": "暂无计划",
    "footer.version": "OpenClaw 任务指挥中心 v2.0 — 开源专案 🦞",
    "footer.credits": "ALTOS LAB 制作",
    "status.loading": "加载中...",
    "status.connected": "已连接",
    "status.disconnected": "已断线",
  },
  "zh-TW": {
    "header.title": "OpenClaw 任務指揮中心",
    "header.subtitle": "代理人儀表板 · 即時監控",
    "header.online": "即時連線",
    "header.offline": "離線",
    "agent.name": "代理人",
    "agent.description": "幹練 · 精確 · 帶點優雅的霸氣 💅",
    "agent.status.offline": "離線",
    "agent.wallet": "錢包",
    "agent.acp": "ACP 狀態",
    "agent.services": "服務項目",
    "agent.skills": "核心技能",
    "taskboard.title": "任務看板",
    "taskboard.inProgress": "進行中",
    "taskboard.planned": "規劃中",
    "taskboard.completed": "已完成",
    "taskboard.empty": "暫無項目",
    "skills.title": "已安裝技能",
    "skills.category": "本地套件",
    "scheduled.title": "排程任務",
    "scheduled.empty": "暫無排程任務",
    "scheduled.lastRun": "上次",
    "scheduled.nextRun": "下次",
    "logs.title": "即時日誌",
    "logs.autoScroll": "自動捲動",
    "logs.clear": "清除",
    "settings.title": "系統設定",
    "settings.gateway": "開道器",
    "settings.models": "模型配置",
    "settings.channels": "頻道與插件",
    "memory.title": "記憶與進化計畫",
    "memory.empty": "暫無計畫",
    "footer.version": "OpenClaw 任務指揮中心 v2.0 — 開源專案 🦞",
    "footer.credits": "ALTOS LAB 製作",
    "footer.buildTime": "最後更新日期",
    "status.loading": "載入中...",
    "status.connected": "已連線",
    "status.disconnected": "已斷線",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("zh-TW");

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
